"""Django settings for revel project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from importlib.metadata import version
from pathlib import Path

import pillow_heif
from decouple import Csv, config

# Register HEIC/HEIF support with Pillow
pillow_heif.register_heif_opener()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
SALT_KEY = config("SALT_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
DEMO_MODE = config("DEMO_MODE", default=DEBUG, cast=bool)

ALLOWED_HOSTS: list[str] = config("ALLOWED_HOSTS", cast=Csv(), default="localhost,127.0.0.1,host.docker.internal")

SILK_PROFILER = config("SILK_PROFILER", default=False, cast=bool)
SILKY_PYTHON_PROFILER = config("SILKY_PYTHON_PROFILER", default=False, cast=bool)

# Throttling - disable for load testing
DISABLE_THROTTLING = config("DISABLE_THROTTLING", default=False, cast=bool)

# System testing mode - exposes tokens in response headers instead of relying on email
SYSTEM_TESTING = config("SYSTEM_TESTING", default=False, cast=bool)

# Application definition

INSTALLED_APPS = [
    "unfold",  # needs to be at the top
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.gis",
    # third party
    "django_prometheus",  # Observability: Prometheus metrics
    "corsheaders",
    "solo",
    "simple_history",
    "django_google_sso",
    "django_celery_results",
    "django_celery_beat",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "ninja_extra",
    "django_extensions",
    # custom
    "api",
    "accounts",
    "common",
    "events",
    "questionnaires",
    "polls",
    "moderation",
    "telegram",
    "geo",
    "notifications",
    "wallet",
]

if SILK_PROFILER:
    INSTALLED_APPS += ["silk"]


SITE_ID = 1
SITE_NAME = config("SITE_NAME", default="Revel")
BASE_URL = config("BASE_URL", default="https://demo.letsrevel.io")
FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://localhost:5173")


MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",  # Observability: Prometheus metrics (must be first)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "common.middleware.UserLanguageMiddleware",
    "common.middleware.StructlogContextMiddleware",  # Observability: request context enrichment
    "common.middleware.TestTokenMiddleware",  # System testing: expose tokens in headers
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "geo.middleware.GeoPointMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",  # Observability: Prometheus metrics (must be last)
]

if SILK_PROFILER:
    MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]


ROOT_URLCONF = "revel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "revel.wsgi.application"
ASGI_APPLICATION = "revel.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PgBouncer configuration
# When using PgBouncer in transaction mode:
# - Set CONN_MAX_AGE to 0 (PgBouncer handles pooling, not Django)
# - Disable CONN_HEALTH_CHECKS (incompatible with transaction mode)
# - Keep ATOMIC_REQUESTS=True (works perfectly with transaction mode)
USE_PGBOUNCER = config("DB_USE_PGBOUNCER", cast=bool, default=False)

_postgres_db = {
    "ENGINE": "django_prometheus.db.backends.postgis",  # Instrumented PostGIS backend for metrics
    "NAME": config("DB_NAME", "revel"),
    "USER": config("DB_USER", "revel"),
    "PASSWORD": config("DB_PASSWORD", "revel-password"),
    "HOST": config("DB_HOST", "localhost"),
    "PORT": config("DB_PORT", "5432"),
    "CONN_MAX_AGE": 0 if USE_PGBOUNCER else config("DB_CONN_MAX_AGE", cast=int, default=60),
    # PgBouncer transaction-pooling mode recycles the backend connection at every
    # COMMIT, which orphans PostgreSQL server-side cursors (Django's QuerySet.iterator()).
    # Django's docs require disabling them in this mode; otherwise a FETCH/CLOSE after a
    # commit raises InvalidCursorName. See docs/postmortems/0002-server-side-cursor-pgbouncer.md and #458.
    "DISABLE_SERVER_SIDE_CURSORS": USE_PGBOUNCER,
    "ATOMIC_REQUESTS": True,
    "OPTIONS": {
        "connect_timeout": 5,
    },
}

# Add CONN_HEALTH_CHECKS only when not using PgBouncer
# (transaction pooling mode doesn't support health checks)
if not USE_PGBOUNCER:
    _postgres_db["CONN_HEALTH_CHECKS"] = config("DB_CONN_HEALTH_CHECKS", cast=bool, default=True)

default_db = _postgres_db

DATABASES = {"default": default_db}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "accounts.password_validation.ComplexPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE", default="en")

LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("it", "Italiano"),
    ("fr", "Français"),
    ("es", "Español"),
    ("pt", "Português"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "Europe/Vienna"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static/"


DEFAULT_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"


STORAGES = {
    "default": {"BACKEND": DEFAULT_STORAGE_BACKEND},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.RevelUser"

# ACCOUNTS
ACCOUNT_OTP_EXPIRATION_MINUTES = config("ACCOUNT_OTP_EXPIRATION_MINUTES", cast=int, default=5)


REDIS_HOST = config("REDIS_HOST", default="localhost")
REDIS_PORT = config("REDIS_PORT", cast=int, default=6379)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
        # Bound every cache op: the default redis-py client has NO timeouts, so a hung
        # (vs refused) Redis would block indefinitely — and the cache sits on every
        # request's hot path via the global throttles (#880). A refused/timed-out op
        # raises instead, which callers either surface (throttling) or absorb
        # (fail-open caches like events.service.permission_snapshot).
        "OPTIONS": {
            "socket_connect_timeout": config("REDIS_SOCKET_CONNECT_TIMEOUT", cast=float, default=1.0),
            "socket_timeout": config("REDIS_SOCKET_TIMEOUT", cast=float, default=1.0),
        },
    }
}

# django-solo: cache the singleton rows (SiteSettings, Legal) in Redis instead of
# hitting the DB on every SingletonModel.get_solo() call. Without this, get_solo()
# runs a get_or_create() per call — which fanned out into 100+ identical
# SELECT common_sitesettings queries inside notification-dispatch loops.
# django-solo refreshes the cache on .save() and clears it on .delete(), so admin
# edits invalidate automatically; the timeout is only a backstop against rows
# mutated directly in the DB (bypassing .save()).
SOLO_CACHE = "default"
SOLO_CACHE_TIMEOUT = 60 * 60  # 1 hour


# GENERAL
VERSION = version("revel")
API_DOCS_URL: str | None = "/docs"

SITE_DOMAIN = config("SITE_DOMAIN", default="localhost")

CORS_ALLOW_CREDENTIALS = True
_cors_origins: list[str] = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())
if _cors_origins and _cors_origins != [""]:
    CORS_ALLOWED_ORIGINS: list[str] = _cors_origins
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    # Custom headers for token-based access
    "x-event-token",
    "x-organization-token",
]

# Expose headers that clients can read from responses
CORS_EXPOSE_HEADERS = [
    "X-Request-ID",
    # System testing headers (only populated when SYSTEM_TESTING=True)
    "X-Test-Verification-Token",
    "X-Test-Password-Reset-Token",
    "X-Test-Deletion-Token",
]
_proto = "http" if DEBUG else "https"
CSRF_TRUSTED_ORIGINS = [f"{_proto}://{SITE_DOMAIN}"]
SERVICE_URL = CSRF_TRUSTED_ORIGINS[0]
SERVICE_URL += ":8000" if "localhost" in SERVICE_URL else ""
SERVICE_DESCRIPTION = config("SERVICE_DESCRIPTION", default="The Revel API")
ADMIN_URL = config("ADMIN_URL", default="admin/")

# OTP
TOTP_ISSUER_NAME = config("TOTP_ISSUER_NAME", default="Revel")


# LLM — see revel/settings/llm.py for configuration details


# DATA UPLOADS
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB


CLAMAV_HOST = config("CLAMAV_HOST", default="localhost")
CLAMAV_PORT = config("CLAMAV_PORT", default=3310, cast=int)

IP2LOCATION_TOKEN = config("IP2LOCATION_TOKEN", default=None)


# NOTIFICATIONS
NOTIFICATION_RETENTION_DAYS = config("NOTIFICATION_RETENTION_DAYS", default=90, cast=int)

# PUSHOVER
PUSHOVER_USER_KEY = config("PUSHOVER_USER_KEY", default=None)
PUSHOVER_APP_TOKEN = config("PUSHOVER_APP_TOKEN", default=None)

# DISCORD
DISCORD_ADMIN_WEBHOOK_URL = config("DISCORD_ADMIN_WEBHOOK_URL", default=None)

DEPLOYMENT_ENVIRONMENT = config(
    "DEPLOYMENT_ENVIRONMENT", default="development" if config("DEBUG", default=False, cast=bool) else "production"
)


if DEPLOYMENT_ENVIRONMENT == "production":
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Submit for HSTS preload list
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
    SECURE_REDIRECT_EXEMPT = [
        r"^metrics/?$",  # Allow Prometheus to scrape metrics via HTTP
        r"^api/healthcheck/?$",  # Allow health checks via HTTP
    ]
    SESSION_COOKIE_SECURE = True  # Only send session cookies over HTTPS
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
