# Generated by Django

from django.db import migrations

PRIVACY_POLICY = """\
## 1. Introdução

A DuRock RJ ("nós", "nosso" ou "Plataforma") é uma plataforma digital que reúne shows de rock \
de diversos organizadores, casas de shows e bandas de todo o estado do Rio de Janeiro, \
permitindo a descoberta de eventos, a confirmação de presença (RSVP) e a compra de ingressos.

Esta Política de Privacidade explica quais dados pessoais coletamos, por que os coletamos, \
como os usamos e quais são os seus direitos, em conformidade com a Lei Geral de Proteção de \
Dados (Lei nº 13.709/2018 – LGPD).

Ao utilizar a DuRock RJ, você concorda com as práticas descritas nesta Política.

## 2. Quais dados coletamos

- **Dados de cadastro**: nome, e-mail e senha (armazenada de forma criptografada) ao criar uma conta.
- **Dados de compra e presença**: ingressos adquiridos, confirmações de presença (RSVP), \
respostas a questionários de evento (quando aplicável) e histórico de participação.
- **Dados de pagamento**: os pagamentos são processados diretamente pelo Stripe, nosso parceiro \
de processamento de pagamentos. Não armazenamos números de cartão de crédito nem dados sensíveis \
de pagamento em nossos servidores.
- **Dados de contato para compras sem cadastro**: quando você compra um ingresso como convidado, \
sem criar conta, coletamos apenas o necessário para emitir e confirmar o ingresso (nome e e-mail).
- **Dados técnicos**: endereço IP, tipo de navegador e cookies estritamente necessários para o \
funcionamento do site (ver seção 9).
- **Comunicações**: mensagens que você envia a organizadores ou ao suporte da Plataforma.

## 3. Como usamos seus dados

Usamos seus dados pessoais para:

- Criar e gerenciar sua conta;
- Processar a compra de ingressos e confirmações de presença;
- Emitir ingressos, incluindo passes para carteira digital (Apple Wallet) e códigos de check-in;
- Enviar comunicações sobre os eventos que você confirmou presença ou comprou ingresso (alterações \
de data/local, cancelamentos, lembretes);
- Disponibilizar sua lista de presença aos organizadores dos eventos correspondentes, para fins \
de check-in e controle de acesso;
- Prevenir fraudes e garantir a segurança da Plataforma;
- Cumprir obrigações legais e regulatórias.

Não utilizamos seus dados para fins de publicidade de terceiros nem os comercializamos.

## 4. Com quem compartilhamos seus dados

- **Organizadores do evento**: ao comprar um ingresso ou confirmar presença em um evento, seus \
dados (nome, e-mail e, quando aplicável, respostas a questionários) são compartilhados com o \
organizador e sua equipe, exclusivamente para gestão do evento e check-in.
- **Processador de pagamentos**: o Stripe processa os pagamentos em nosso nome, sob suas próprias \
políticas de privacidade e segurança (certificação PCI-DSS).
- **Prestadores de serviço**: utilizamos fornecedores para envio de e-mails transacionais e \
hospedagem de dados, sempre sob contrato e obrigação de confidencialidade.
- **Autoridades competentes**: quando exigido por lei, ordem judicial, ou para proteger direitos, \
segurança e propriedade da DuRock RJ ou de terceiros.

Nunca vendemos seus dados pessoais a terceiros.

## 5. Base legal para o tratamento (LGPD)

Tratamos seus dados com base em uma ou mais das hipóteses legais do art. 7º da LGPD: execução \
de contrato (compra de ingressos, criação de conta), consentimento (ex.: inscrição em \
notificações opcionais), cumprimento de obrigação legal ou regulatória, e legítimo interesse \
(ex.: prevenção a fraudes).

## 6. Por quanto tempo guardamos seus dados

Mantemos seus dados pelo tempo necessário para cumprir as finalidades descritas nesta Política, \
incluindo o período exigido por obrigações legais, fiscais e contábeis (ex.: registros de venda \
de ingressos). Após esse período, os dados são excluídos ou anonimizados.

## 7. Seus direitos

Como titular de dados, você pode, a qualquer momento:

- Confirmar a existência de tratamento e acessar seus dados;
- Corrigir dados incompletos, inexatos ou desatualizados;
- Solicitar a exclusão ou anonimização de dados desnecessários;
- Solicitar a portabilidade dos seus dados;
- Revogar o consentimento dado e se opor a tratamentos realizados com base em legítimo interesse;
- Solicitar informações sobre com quem compartilhamos seus dados.

Você pode exercer esses direitos diretamente pela sua conta (em "Configurações" e "Privacidade") \
ou entrando em contato conosco pelos canais indicados na seção 12.

## 8. Segurança

Adotamos medidas técnicas e organizacionais para proteger seus dados contra acesso não \
autorizado, perda, alteração ou destruição, incluindo criptografia de senhas, controle de acesso \
e monitoramento contínuo. Nenhum sistema é 100% seguro, e nos comprometemos a notificar você e \
as autoridades competentes em caso de incidentes de segurança que possam gerar risco relevante.

## 9. Cookies

Utilizamos apenas cookies estritamente necessários para autenticação e funcionamento do site \
(por exemplo, para manter sua sessão ativa). Não utilizamos cookies de rastreamento publicitário \
de terceiros.

## 10. Menores de idade

A DuRock RJ não é destinada a menores de 18 anos sem a supervisão de um responsável legal. \
Alguns eventos divulgados na Plataforma podem ter classificação etária própria, definida pelo \
organizador, que deve ser respeitada independentemente do uso da Plataforma.

## 11. Alterações nesta Política

Podemos atualizar esta Política periodicamente. Alterações relevantes serão comunicadas por \
e-mail ou por aviso na Plataforma. A data da última atualização estará sempre indicada ao final \
deste documento.

## 12. Contato

Dúvidas, solicitações relacionadas aos seus dados pessoais ou reclamações podem ser enviadas \
para: **[e-mail de contato / encarregado de dados a definir]**.

*Última atualização: 10 de julho de 2026*
"""

TERMS_OF_SERVICE = """\
## 1. Aceitação dos termos

Estes Termos de Serviço regulam o uso da plataforma DuRock RJ ("Plataforma"), que reúne shows \
de rock de diversos organizadores, casas de shows e bandas de todo o estado do Rio de Janeiro. \
Ao criar uma conta, confirmar presença ou comprar um ingresso pela Plataforma, você concorda \
integralmente com estes Termos.

## 2. O que é a DuRock RJ

A DuRock RJ é uma plataforma de descoberta e gestão de eventos que conecta organizadores, casas \
de shows e bandas ao público interessado em shows de rock. Oferecemos:

- Divulgação e descoberta de eventos de diversos organizadores;
- Confirmação de presença (RSVP) para eventos gratuitos;
- Venda de ingressos para eventos pagos, com emissão de ingresso digital e QR code para check-in;
- Perfis de organizações, com gestão de membros e comunicação com o público.

A DuRock RJ atua como **intermediária tecnológica** entre organizadores e o público. Salvo \
quando expressamente indicado, **não somos a produtora, organizadora ou responsável pela \
realização dos eventos** divulgados na Plataforma.

## 3. Cadastro e conta

Para comprar ingressos ou confirmar presença, você pode criar uma conta ou, em eventos que \
permitirem, prosseguir como convidado, informando apenas os dados necessários para emissão do \
ingresso. Você é responsável por manter a confidencialidade de sua senha e por todas as \
atividades realizadas em sua conta. As informações fornecidas no cadastro devem ser verdadeiras, \
completas e atualizadas.

## 4. Responsabilidade dos organizadores

Cada evento divulgado na Plataforma é de responsabilidade exclusiva do organizador que o \
cadastrou, incluindo:

- A veracidade das informações divulgadas (data, local, line-up, classificação etária, etc.);
- A realização efetiva do evento nas condições anunciadas;
- A definição e o cumprimento da política de cancelamento e reembolso de cada nível de ingresso;
- O atendimento a obrigações legais aplicáveis ao evento (licenças, direitos autorais de \
execução musical, segurança do local, etc.).

A DuRock RJ não garante e não se responsabiliza pela qualidade, segurança, legalidade ou efetiva \
realização dos eventos divulgados por terceiros.

## 5. Compra de ingressos e pagamentos

- Os pagamentos de ingressos pagos são processados pelo Stripe, parceiro de pagamentos da \
Plataforma.
- Quando aplicável, uma **taxa de serviço** é somada ao valor do ingresso e exibida \
separadamente na tela de finalização da compra, antes da confirmação do pagamento.
- O ingresso é confirmado por e-mail e disponibilizado na sua conta, podendo incluir código QR \
para check-in e, quando disponível, passe para carteira digital.
- Cada organizador define sua própria política de cancelamento e reembolso por nível de \
ingresso, exibida antes da compra. Consulte-a antes de concluir sua compra.

## 6. Cancelamento e alteração de eventos

Caso um organizador cancele ou altere substancialmente um evento, ele é responsável por \
comunicar os participantes e processar eventuais reembolsos, conforme sua política. A DuRock RJ \
pode auxiliar na comunicação e, quando tecnicamente aplicável, no processamento de estornos via \
Stripe, mas não é a responsável financeira pelo reembolso, exceto quando a própria DuRock RJ for \
a organizadora do evento.

## 7. Conduta do usuário

Ao usar a Plataforma, você concorda em não:

- Fornecer informações falsas ou se passar por terceiros;
- Revender ingressos com fins especulativos fora dos mecanismos oferecidos pela Plataforma;
- Utilizar a Plataforma para fins fraudulentos, ilegais ou que violem direitos de terceiros;
- Tentar acessar áreas restritas, contornar medidas de segurança ou interferir no funcionamento \
da Plataforma.

O descumprimento destas regras pode resultar em suspensão ou encerramento da sua conta, sem \
prejuízo de outras medidas legais cabíveis.

## 8. Propriedade intelectual

A marca "DuRock RJ", seu layout, design e código são de propriedade da Plataforma ou de seus \
licenciadores. Conteúdos enviados por organizadores (descrições, imagens, line-ups) permanecem \
de propriedade destes, que garantem possuir os direitos necessários para publicá-los.

## 9. Limitação de responsabilidade

Na máxima extensão permitida pela lei, a DuRock RJ não se responsabiliza por danos indiretos, \
lucros cessantes ou prejuízos decorrentes da realização, cancelamento ou alteração de eventos \
por organizadores terceiros, nem por indisponibilidades temporárias da Plataforma por motivos \
técnicos ou de força maior.

## 10. Suspensão e encerramento

Podemos suspender ou encerrar contas que violem estes Termos, mediante aviso prévio sempre que \
possível. Você pode encerrar sua conta a qualquer momento pelas configurações de conta.

## 11. Alterações nestes Termos

Podemos atualizar estes Termos periodicamente. Alterações relevantes serão comunicadas por \
e-mail ou aviso na Plataforma, com a data da última atualização indicada ao final deste \
documento.

## 12. Lei aplicável e foro

Estes Termos são regidos pelas leis da República Federativa do Brasil. Fica eleito o foro da \
comarca do Rio de Janeiro/RJ para dirimir quaisquer controvérsias, com renúncia a qualquer \
outro, por mais privilegiado que seja.

## 13. Contato

Dúvidas sobre estes Termos podem ser enviadas para: **[e-mail de contato a definir]**.

*Última atualização: 10 de julho de 2026*
"""


def seed_legal_documents(apps, schema_editor):
    """Seed the Legal singleton with DuRock RJ's privacy policy and terms of service.

    Only fills in fields that are still empty, so it never clobbers content
    an admin has already edited through the Django admin.
    """
    Legal = apps.get_model("common", "Legal")
    legal, _ = Legal.objects.get_or_create(pk=1)
    changed_fields = []
    if not legal.privacy_policy:
        legal.privacy_policy = PRIVACY_POLICY
        changed_fields.append("privacy_policy")
    if not legal.terms_and_conditions:
        legal.terms_and_conditions = TERMS_OF_SERVICE
        changed_fields.append("terms_and_conditions")
    if changed_fields:
        legal.save(update_fields=changed_fields)


def reverse_seed(apps, schema_editor):
    """No-op: we don't know if the content was ours or an admin's later edit."""


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_alter_fileexport_export_type"),
    ]

    operations = [
        migrations.RunPython(
            seed_legal_documents,
            reverse_code=reverse_seed,
        ),
    ]
