# Generated by Django 5.2.17 on 2026-08-13 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('durock', '0002_translate_default_membership_tier_name'),
        ('events', '0115_remove_organization_bluesky_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPixConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pix_key', models.CharField(help_text='CPF, CNPJ, e-mail, telefone ou chave aleatória (EVP) que recebe o pagamento.', max_length=140)),
                ('merchant_name', models.CharField(help_text='Nome do recebedor como aparece no app do banco (máx. 25 caracteres).', max_length=25)),
                ('merchant_city', models.CharField(help_text='Cidade do recebedor (máx. 15 caracteres).', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para parar de oferecer Pix sem apagar a chave.')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_config', to='events.organization')),
            ],
            options={
                'verbose_name': 'configuração Pix',
                'verbose_name_plural': 'configurações Pix',
            },
        ),
        migrations.CreateModel(
            name='PixCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('txid', models.CharField(editable=False, help_text='Referência que o organizador vê no extrato para conciliar o pagamento.', max_length=25, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Valor congelado na emissão do QR.', max_digits=10)),
                ('payload', models.TextField(editable=False)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_charge', to='events.ticket')),
            ],
            options={
                'verbose_name': 'cobrança Pix',
                'verbose_name_plural': 'cobranças Pix',
            },
        ),
    ]
