# Generated by Django 5.2.15 on 2026-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0114_event_place_of_supply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="bluesky_url",
        ),
        migrations.AddField(
            model_name="organization",
            name="whatsapp_url",
            field=models.URLField(blank=True, null=True, verbose_name="WhatsApp"),
        ),
        migrations.AddField(
            model_name="organization",
            name="youtube_url",
            field=models.URLField(blank=True, null=True, verbose_name="YouTube"),
        ),
    ]
